const csc = '최순철'
const hsg = '한슬기'
const progress = '진행중'
const incomplate = '미완료'
const complate = '완료'
const v20190626 = '2019.06.26'
const btn = '보기'
const table = [
  {
    'no': '',
    'depth1': '공통',
    'depth2': '',
    'depth3': '',
    'title': '레이아웃',
    'html': '/common/layoutCommon',
    'process': progress,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '대시보드',
    'depth2': '',
    'depth3': '',
    'title': '',
    'html': '/display/promotion/list',
    'process': incomplate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '전시 관리',
    'depth2': '프로모션 관리',
    'depth3': '',
    'title': '프로모션 목록',
    'html': '/display/promotion/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '프로모션 상세',
    'html': '/display/promotion/view',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '프로모션 등록/수정',
    'html': '/display/promotion/edit',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'Suggest 관리',
    'depth3': '',
    'title': 'Suggest 목록',
    'html': '/display/suggest/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'Suggest 등록/수정',
    'html': '/display/suggest/edit',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'Discover 관리',
    'depth3': '',
    'title': 'Discover 목록',
    'html': '/display/discover/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '위젯 관리',
    'depth3': '',
    'title': '위젯 목록',
    'html': '/display/widget/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 날씨',
    'html': '/display/widget/edit/weather',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 국내축구',
    'html': '/display/widget/edit/soccer',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 해외축구',
    'html': '/display/widget/edit/overseassoccer',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 국내농구',
    'html': '/display/widget/edit/basketball',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 해외농구',
    'html': '/display/widget/edit/overseasbasketball',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '위젯 수정: 오늘의 명언',
    'html': '/display/widget/edit/saying',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '콘텐츠 관리',
    'depth2': 'Line 관리',
    'depth3': '',
    'title': 'Line 목록',
    'html': '/contants/line/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'Line 상세',
    'html': '/contants/line/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'Line 등록/수정',
    'html': '/contants/line/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '콘텐츠 관리',
    'depth3': '',
    'title': '콘텐츠 목록',
    'html': '/contants/contants/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 상세',
    'html': '/contants/contants/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: 유튜브',
    'html': '/contants/contants/editYoutube',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: ASMR',
    'html': '/contants/contants/editAsmr',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: 일반게시물',
    'html': '/contants/contants/editBasic',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: 리스티클',
    'html': '/contants/contants/editList',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: 카드뉴스',
    'html': '/contants/contants/editCard',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '콘텐츠 등록/수정: 인터렉티브',
    'html': '/contants/contants/editInteractive',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '태그 관리',
    'depth3': '',
    'title': '태그 관리',
    'html': '/contants/tag/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '검색어 관리',
    'depth3': '',
    'title': '인기 검색어 관리',
    'html': '/contants/search/bestList',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'Placeholder 관리',
    'html': '/contants/search/placeholderList',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'CP 관리',
    'depth3': '',
    'title': 'CP 목록',
    'html': '/cp/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'CP 상세',
    'html': '/cp/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': 'CP 등록/수정',
    'html': '/cp/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '이벤트 관리',
    'depth3': '',
    'title': '이벤트 목록',
    'html': '/event/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '이벤트 상세',
    'html': '/event/view',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '이벤트 등록/수정',
    'html': '/event/edit',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '서비스 관리',
    'depth2': '공지사항',
    'depth3': '',
    'title': '목록',
    'html': '/service/notice/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/notice/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/notice/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '서비스 점검',
    'depth3': '',
    'title': '목록',
    'html': '/service/workout/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/workout/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/workout/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'FAQ',
    'depth3': '',
    'title': '목록',
    'html': '/service/faq/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/faq/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/faq/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '1:1문의 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/inquiry/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/inquiry/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/inquiry/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '약관 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/terms/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/terms/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록',
    'html': '/service/terms/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '수정: 전시 전 약관',
    'html': '/service/terms/modifibefore',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '수정: 전시 중 약관',
    'html': '/service/terms/modifiafter',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '금칙어 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/forbidden/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/forbidden/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '어드민 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/admin/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/admin/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'Push 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/push/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '상세',
    'html': '/service/push/view',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/push/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': 'App 버전 관리',
    'depth3': '',
    'title': '목록',
    'html': '/service/app/list',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '등록/수정',
    'html': '/service/app/edit',
    'process': complate,
    'manager': csc,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '회원 관리',
    'depth2': '회원 관리',
    'depth3': '',
    'title': '회원 목록',
    'html': '/member/single/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '회원 상세',
    'html': '/member/single/view',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '댓글 관리',
    'depth3': '',
    'title': '목록',
    'html': '/member/comment/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '통계 관리',
    'depth2': '회원 통계',
    'depth3': '',
    'title': '가입자',
    'html': '/statistics/member/join',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '',
    'depth3': '',
    'title': '탈퇴자',
    'html': '/statistics/member/secession',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '콘텐츠 랭킹',
    'depth3': '',
    'title': '콘텐츠 기준/Line기준/CP기준',
    'html': '/statistics/contants/ranking',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '전시콘텐츠 통계',
    'depth3': '',
    'title': 'Suggest/Discover',
    'html': '/statistics/display/titles',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '유틸리티',
    'depth2': '마이페이지',
    'depth3': '',
    'title': '등록',
    'html': '/utility/mypage/list',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  },
  {
    'no': '',
    'depth1': '',
    'depth2': '로그인',
    'depth3': '',
    'title': '로그인',
    'html': '/utility/login/index',
    'process': complate,
    'manager': hsg,
    'note': ``,
    'version': v20190626,
    'popup': btn
  }
]
export default table
